apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-service
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
