apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-8fssv
    field.cattle.io/publicEndpoints: '[{"addresses":["172.22.1.114"],"port":32191,"protocol":"TCP","serviceName":"nginx-ns:pfe-deployment-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-nginx-ns-pfe-deployment
  name: pfe-deployment
  selfLink: /apis/apps/v1beta2/namespaces/nginx-ns/deployments/pfe-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-nginx-ns-pfe-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"pfe-deployment-nodeport","kind":"NodePort","name":"8080tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-nginx-ns-pfe-deployment
    spec:
      containers:
      - image: slnvmrt01.ntes.fr.sopra:4444/pfe_tomcat
        imagePullPolicy: Always
        name: pfe-deployment
        ports:
        - containerPort: 8080
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
