apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: pfe-service
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: pfe-tomcat-remote
  type: NodePort
status:
  loadBalancer: {}
