version: '2'
services: 
  tomcat:
    container_name: tomcat_pfe
    image: tomcat:latest
    ports: 
      - "8090:8080"
    volumes:
      - ./src/ws-a/target/ws-a.war:/usr/local/tomcat/webapps/ws-a.war
      - ./src/ws-b/target/ws-b.war:/usr/local/tomcat/webapps/ws-b.war
      - ./src/ws-c/target/ws-c.war:/usr/local/tomcat/webapps/ws-c.war
      - ./src/ws-d/target/ws-d.war:/usr/local/tomcat/webapps/ws-d.war
