version: '2'
services: 
  tomcat-local:
    container_name: pfe-ws
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./src/ws-a/target/ws-a.war:/usr/local/tomcat/webapps/ws-a.war
      - ./src/ws-b/target/ws-b.war:/usr/local/tomcat/webapps/ws-b.war

